name: nateageek-website
recipe: drupal9
config:
  webroot: ./drupal
proxy:
  gatsby:
    - gatsby-nateageek.lndo.site:8000
  appserver:
    - drupal-nateageek.lndo.site
services:
  gatsby:
    type: node
    port: 3000
    globals:
      gatsby-cli: latest
    build: cd gatsby && npm install
    command: cd gatsby && npm run develop
tooling:
  drush:
    service: appserver
    cmd: drush drush --root=/app/drupal
  npm:
    service: gatsby
    cmd: cd gatsby && npm
  npx:
    service: gatsby
    cmd: cd gatsby && npx
  gatsby:
    service: gatsby
    cmd: cd gatsby && gatsby
