name: nateageek-website
recipe: drupal9
config:
  webroot: ./drupal
proxy:
  gatsby:
    - gatsby-nateageek.lndo.site:8000
    - gatsby-nateageek.lndo.site:40281
  appserver:
    - drupal-nateageek.lndo.site
services:
  gatsby:
    type: node
    port: 8000
    globals:
      gatsby-cli: latest
    build: 
      - "cd gatsby && npm install"
    command: "cd gatsby && npm run develop"
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/drupal
  npm:
    service: gatsby
    cmd: npm
  npx:
    service: gatsby
    cmd: npx
  gatsby:
    service: gatsby
    cmd: gatsby
